'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Empleados
    Public Property Id As Integer
    Public Property NombreCompleto As String
    Public Property TipoIdentificacion As String
    Public Property NumeroIdentificacion As String
    Public Property FechaIngreso As Nullable(Of Date)
    Public Property SalarioBaseMensual As Nullable(Of Decimal)
    Public Property Direccion As String

    Public Overridable Property Vacaciones As ICollection(Of Vacaciones) = New HashSet(Of Vacaciones)

End Class
