'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class GestionDeEmpleadosEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=GestionDeEmpleadosEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Empleados() As DbSet(Of Empleados)
    Public Overridable Property Vacaciones() As DbSet(Of Vacaciones)
    Public Overridable Property vw_empleados() As DbSet(Of vw_empleados)

    Public Overridable Function sp_InsertarEmpleado(nombreCompleto As String, tipoIdentificacion As String, numeroIdentificacion As String, fechaIngreso As Nullable(Of Date), salarioBaseMensual As Nullable(Of Decimal), direccion As String) As Integer
        Dim nombreCompletoParameter As ObjectParameter = If(nombreCompleto IsNot Nothing, New ObjectParameter("NombreCompleto", nombreCompleto), New ObjectParameter("NombreCompleto", GetType(String)))

        Dim tipoIdentificacionParameter As ObjectParameter = If(tipoIdentificacion IsNot Nothing, New ObjectParameter("TipoIdentificacion", tipoIdentificacion), New ObjectParameter("TipoIdentificacion", GetType(String)))

        Dim numeroIdentificacionParameter As ObjectParameter = If(numeroIdentificacion IsNot Nothing, New ObjectParameter("NumeroIdentificacion", numeroIdentificacion), New ObjectParameter("NumeroIdentificacion", GetType(String)))

        Dim fechaIngresoParameter As ObjectParameter = If(fechaIngreso.HasValue, New ObjectParameter("FechaIngreso", fechaIngreso), New ObjectParameter("FechaIngreso", GetType(Date)))

        Dim salarioBaseMensualParameter As ObjectParameter = If(salarioBaseMensual.HasValue, New ObjectParameter("SalarioBaseMensual", salarioBaseMensual), New ObjectParameter("SalarioBaseMensual", GetType(Decimal)))

        Dim direccionParameter As ObjectParameter = If(direccion IsNot Nothing, New ObjectParameter("Direccion", direccion), New ObjectParameter("Direccion", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_InsertarEmpleado", nombreCompletoParameter, tipoIdentificacionParameter, numeroIdentificacionParameter, fechaIngresoParameter, salarioBaseMensualParameter, direccionParameter)
    End Function

    Public Overridable Function sp_Vacaciones(empleadoId As Nullable(Of Integer), fechaInicio As Nullable(Of Date), fechaFinal As Nullable(Of Date)) As Integer
        Dim empleadoIdParameter As ObjectParameter = If(empleadoId.HasValue, New ObjectParameter("EmpleadoId", empleadoId), New ObjectParameter("EmpleadoId", GetType(Integer)))

        Dim fechaInicioParameter As ObjectParameter = If(fechaInicio.HasValue, New ObjectParameter("FechaInicio", fechaInicio), New ObjectParameter("FechaInicio", GetType(Date)))

        Dim fechaFinalParameter As ObjectParameter = If(fechaFinal.HasValue, New ObjectParameter("FechaFinal", fechaFinal), New ObjectParameter("FechaFinal", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_Vacaciones", empleadoIdParameter, fechaInicioParameter, fechaFinalParameter)
    End Function

End Class
